### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/staudenmeir/laravel-upsert/pull/36/commits/5473cb497cf20fa29262dd3abbc32b8e73b2e7b3?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-upsert.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "staudenmeir/laravel-upsert": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by staudenmeir** [comment]
The package doesn't work with Laravel 9: https://github.com/staudenmeir/laravel-upsert/issues/26#issuecomment-709242756

**Comment by jasonmccreary** [comment]
@staudenmeir, gotcha. Thanks. I'll make a note on Shift's side.

**Comment by staudenmeir** [comment]
Hi @deevus,
This is actually not an issue with the Laravel implementation – that's how MySQL's (only) upsert feature works. There's no workaround for that.

**Comment by deevus** [comment]
Right. The part that's confusing me then is that our codebase is using `upsert` with Laravel 8 and MySQL and it works fine. Upgrading to Laravel 9 and now upsert doesn't work.

**Comment by staudenmeir** [comment]
Maybe it's related to this change? https://github.com/laravel/framework/pull/42053

**Comment by deevus** [comment]
Don't think so. As far as I can tell that's an opt-in change where you need to set `use_upsert_alias` to true in the `mysql` config.

**Comment by staudenmeir** [comment]
In any case: If there's an issue with the Laravel 9 implementation, it needs to be fixed there. The package can't take care of that.

**Comment by deevus** [comment]
No worries thanks for your help

**Pull request closed without merging**
